// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrcpIp_npC1iaoqdOfJnY6NqfWRqrl9g',
    appId: '1:214380733427:web:7c0f3db53ae87098876886',
    messagingSenderId: '214380733427',
    projectId: 'notes-8dd2c',
    authDomain: 'notes-8dd2c.firebaseapp.com',
    storageBucket: 'notes-8dd2c.firebasestorage.app',
    measurementId: 'G-HZS5YT2HJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8hc6waz_E349iHoZxdWCV6xxC4JCxi8',
    appId: '1:214380733427:android:4320a067415475ac876886',
    messagingSenderId: '214380733427',
    projectId: 'notes-8dd2c',
    storageBucket: 'notes-8dd2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrpw5UMOJEWx1PgcqfJnPRXXnTY1DLDI',
    appId: '1:214380733427:ios:c15bbe145eafb619876886',
    messagingSenderId: '214380733427',
    projectId: 'notes-8dd2c',
    storageBucket: 'notes-8dd2c.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrpw5UMOJEWx1PgcqfJnPRXXnTY1DLDI',
    appId: '1:214380733427:ios:c15bbe145eafb619876886',
    messagingSenderId: '214380733427',
    projectId: 'notes-8dd2c',
    storageBucket: 'notes-8dd2c.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTrcpIp_npC1iaoqdOfJnY6NqfWRqrl9g',
    appId: '1:214380733427:web:7b90d569bffc6bd9876886',
    messagingSenderId: '214380733427',
    projectId: 'notes-8dd2c',
    authDomain: 'notes-8dd2c.firebaseapp.com',
    storageBucket: 'notes-8dd2c.firebasestorage.app',
    measurementId: 'G-VZSB8G4NB0',
  );
}
