// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLfNm6jdZSJFhKjZ2ixWOHgKwpcDzJS5g',
    appId: '1:597948679823:web:4141ca06b6e8f5ce0f92fa',
    messagingSenderId: '597948679823',
    projectId: 'daftarbelanja-2f3e2',
    authDomain: 'daftarbelanja-2f3e2.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-2f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2f3e2.firebasestorage.app',
    measurementId: 'G-3KDP30PBP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdyN3ex70LLKGklUmPPsls6pPd-bKx2E',
    appId: '1:597948679823:android:ce1732f14a426cc60f92fa',
    messagingSenderId: '597948679823',
    projectId: 'daftarbelanja-2f3e2',
    databaseURL: 'https://daftarbelanja-2f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2f3e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9PtejcDTpSgN2gX7PEXsa4L4M4gqbaIw',
    appId: '1:597948679823:ios:3670ac0dfb6d14040f92fa',
    messagingSenderId: '597948679823',
    projectId: 'daftarbelanja-2f3e2',
    databaseURL: 'https://daftarbelanja-2f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2f3e2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9PtejcDTpSgN2gX7PEXsa4L4M4gqbaIw',
    appId: '1:597948679823:ios:3670ac0dfb6d14040f92fa',
    messagingSenderId: '597948679823',
    projectId: 'daftarbelanja-2f3e2',
    databaseURL: 'https://daftarbelanja-2f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2f3e2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLfNm6jdZSJFhKjZ2ixWOHgKwpcDzJS5g',
    appId: '1:597948679823:web:6cd2191ca51866900f92fa',
    messagingSenderId: '597948679823',
    projectId: 'daftarbelanja-2f3e2',
    authDomain: 'daftarbelanja-2f3e2.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-2f3e2-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-2f3e2.firebasestorage.app',
    measurementId: 'G-QJBBMYHR4Q',
  );
}
