// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zEXAzzSJwgt3OkyKNtP8M6UDELMCyJk',
    appId: '1:835843032856:web:5c3196ead0e13981d2406d',
    messagingSenderId: '835843032856',
    projectId: 'mdpgold-5f357',
    authDomain: 'mdpgold-5f357.firebaseapp.com',
    databaseURL: 'https://mdpgold-5f357-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5f357.firebasestorage.app',
    measurementId: 'G-2P7G23Y6XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfXurxhONtyUI5agTw7JEbNDNOlQ2V-ZE',
    appId: '1:835843032856:android:0d4305679bb05abcd2406d',
    messagingSenderId: '835843032856',
    projectId: 'mdpgold-5f357',
    databaseURL: 'https://mdpgold-5f357-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5f357.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4m366Orri_IGlTmRWI6b2_Mr6oXcJMw',
    appId: '1:835843032856:ios:bb5403e27cddbab1d2406d',
    messagingSenderId: '835843032856',
    projectId: 'mdpgold-5f357',
    databaseURL: 'https://mdpgold-5f357-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5f357.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4m366Orri_IGlTmRWI6b2_Mr6oXcJMw',
    appId: '1:835843032856:ios:bb5403e27cddbab1d2406d',
    messagingSenderId: '835843032856',
    projectId: 'mdpgold-5f357',
    databaseURL: 'https://mdpgold-5f357-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5f357.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zEXAzzSJwgt3OkyKNtP8M6UDELMCyJk',
    appId: '1:835843032856:web:0c50966c808d21b8d2406d',
    messagingSenderId: '835843032856',
    projectId: 'mdpgold-5f357',
    authDomain: 'mdpgold-5f357.firebaseapp.com',
    databaseURL: 'https://mdpgold-5f357-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-5f357.firebasestorage.app',
    measurementId: 'G-0N5QCTNN69',
  );
}
